# Generated by Django 4.2.7 on 2025-09-21 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the listing', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the listing', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the property')),
                ('location', models.CharField(help_text='Location of the property', max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bedrooms', models.PositiveIntegerField(help_text='Number of bedrooms', validators=[django.core.validators.MinValueValidator(1)])),
                ('bathrooms', models.PositiveIntegerField(help_text='Number of bathrooms', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_guests', models.PositiveIntegerField(help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('condo', 'Condominium'), ('cabin', 'Cabin'), ('studio', 'Studio')], default='apartment', help_text='Type of property', max_length=20)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
                ('available', models.BooleanField(default=True, help_text='Whether the listing is currently available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the listing was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the listing was last updated')),
                ('host', models.ForeignKey(help_text='Host who owns this listing', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the booking', primary_key=True, serialize=False)),
                ('check_in_date', models.DateField(help_text='Check-in date')),
                ('check_out_date', models.DateField(help_text='Check-out date')),
                ('number_of_guests', models.PositiveIntegerField(help_text='Number of guests for this booking', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the booking', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Special requests from the guest')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the booking was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the booking was last updated')),
                ('guest', models.ForeignKey(help_text='Guest who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Listing being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the review', primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the review was last updated')),
                ('booking', models.OneToOneField(help_text='Booking this review is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='listings.booking')),
                ('guest', models.ForeignKey(help_text='Guest who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Listing being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='listings_re_rating_d53460_idx'), models.Index(fields=['created_at'], name='listings_re_created_4808d6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location'], name='listings_li_locatio_4bc07d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_per_night'], name='listings_li_price_p_278f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property_type'], name='listings_li_propert_7a505c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['available'], name='listings_li_availab_f5f929_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date'], name='listings_bo_check_i_c96d06_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_out_date'], name='listings_bo_check_o_03286c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='listings_bo_status_8650c6_idx'),
        ),
    ]
